### ISSUE TITLE
When the application being profiled is finished it is impossible to recompile it as its pdb is locked.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tyoma/micro-profiler#8] opened 2015-05-12 16:32 UTC
```
The profiler's window locks application pdb. To proceed with compilation one 
must close the window.
The expected behavior is that the user shall be able to recompile the 
application even, if profiler's window is open.

```

Original issue reported on code.google.com by `artem.ge...@gmail.com` on 10 Apr 2012 at 11:04

**Comment by tyoma** [comment] 2015-08-19 16:59
Duplicate of a defect tracked.

**Comment by tyoma** [comment] 2018-11-25 00:42
Hi!
I have made a small release, that caches symbols upon application exit and releases PDBs. This does not handle abnormal application termination (or terminate from debugger). This will be fixed later.
Please find the release here: https://github.com/tyoma/micro-profiler/releases/tag/v1.4.604.0
Thank you!

**Comment by rold2007** [comment] 2018-12-06 12:00
I had the opportunity to try it today and it worked as expected. Thanks a lot !

**Comment by tyoma** [comment] 2018-12-06 16:07
Thanks!
I'll leave this opened until the underlying functionality is made asynchronous (for .pdb >100MB it takes significant time to read the symbols, and now it just freezes the UI).

**Comment by tyoma** [comment] 2019-09-24 23:48
In 1.5 the debug info is requested asynchronously and then released, so that the application can be rebuilt immediately after profiling session.

**Closed** 2019-09-24 23:52 UTC
Labels: defect, duplicate, from googlecode.com
